language: python
sudo: false
cache: pip
env:
  global:
    - LD_PRELOAD=/lib/x86_64-linux-gnu/libSegFault.so
    - SEGFAULT_SIGNALS=all
  matrix:
    - TOXENV=check
    - TOXENV=docs
matrix:
  include:
    - python: '2.7'
      env:
        - TOXENV=2.7-test-cover,report,coveralls
    - python: '2.7'
      env:
        - TOXENV=2.7-test-nocov
    - python: '3.5'
      env:
        - TOXENV=3.5-test-cover,report,coveralls
    - python: '3.5'
      env:
        - TOXENV=3.5-test-nocov
    - python: '3.6'
      env:
        - TOXENV=3.6-test-cover,report,coveralls
    - python: '3.6'
      env:
        - TOXENV=3.6-test-nocov
    - python: '3.7'
      dist: xenial
      sudo: true
      env:
        - TOXENV=3.7-test-cover,report,coveralls
    - python: '3.7'
      dist: xenial
      sudo: true
      env:
        - TOXENV=3.7-test-nocov
    - python: 'pypy-5.4'
      env:
        - TOXENV=pypy-test-cover,report,coveralls
    - python: 'pypy-5.4'
      env:
        - TOXENV=pypy-test-nocov
before_install:
  - python --version
  - uname -a
  - lsb_release -a
install:
  - pip install tox
  - virtualenv --version
  - easy_install --version
  - pip --version
  - tox --version
script:
  - tox -v
after_failure:
  - more .tox/log/* | cat
  - more .tox/*/log/* | cat
notifications:
  email:
    on_success: never
    on_failure: always
